default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jogether2_development

test:
  <<: *default
  database: jogether2_test

production:
  <<: *default
  database: jogether2_production
  username: jogether2
  password: <%= ENV['AAAA_DATABASE_PASSWORD'] %>

